### ISSUE TITLE
Mention that running both cargo watch and a language server might be bad

### ISSUE THREAD

**Issue by passcod** [yoshuawuyts/rust-for-js-people#5]
Actually, I'm not entirely sure if that's the case with RA. But as of my last experience with RLS it definitely was! My understanding:

Builds (and similar: checks, tests (because they have to build), etc) take a lock on the project, so if two builds try to run at the same time, they'll contend. And locks are released and taken "between" steps (not super sure how that goes in RLS, but with e.g. `cargo watch -x check -x test` the lock will be released briefly between check and test). And language servers want to run a whole lot more often. Kinda creates a mess: cargo watch feels slow, RLS feels slow, because they're often fighting for the lock.

Dunno how to word that in a nice simple friendly way for this guide, but it may be helpful to know given they're both mentioned.

**Comment by yoshuawuyts** [comment]
@passcod that's a fair point! -- my understanding is however that currently there's not much that can be done here, and active steps are being taken to solve this (by making `rust-analyzer` and `rustc` use the same infrastructure). Personally I do run both together all the time, and while not ideal, it beats trying to figure out how to shut down the lang server when doing a local check.

I think what you're saying is not wrong. But I'm also not sure how to share it since there's not really much actionable that can be done here. I'll think about this for a bit; but thanks either way!

**Comment by passcod** [comment]
That's fair :+1:

**Comment by yoshuawuyts** [comment]
I've been thinking about this a bit more, and I'm still unsure what we could do to improve here. I think waiting for the tooling to catch up is probably right.

Going to go ahead and close this. Thanks again!
